// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wirdgdsbwzycectslnha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcmRnZHNid3p5Y2VjdHNsbmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzQ4NjIsImV4cCI6MjA2MzA1MDg2Mn0.1jUU322FQjJk6xIaKuCdvmgp6qG6yOG8mtVkzFEelPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});